INSERT INTO PRODUCT (NAME, DESC, BRAND, PRICE, CATEGORY, RELEASE_DATE, AVAILABLE, QUANTITY)
VALUES ('Tata Nexon', 'Compact SUV with great mileage', 'Tata Motors', 1200000, 'Cars', '2023-03-15', TRUE, 10);

INSERT INTO PRODUCT (NAME, DESC, BRAND, PRICE, CATEGORY, RELEASE_DATE, AVAILABLE, QUANTITY)
VALUES ('Swift', 'Reliable hatchback car', 'Maruti Suzuki', 700000, 'Cars', '2022-08-20', TRUE, 15);

INSERT INTO PRODUCT (NAME, DESC, BRAND, PRICE, CATEGORY, RELEASE_DATE, AVAILABLE, QUANTITY)
VALUES ('Creta', 'Stylish mid-size SUV', 'Hyundai', 1600000, 'Cars', '2023-05-10', TRUE, 8);

INSERT INTO PRODUCT (NAME, DESC, BRAND, PRICE, CATEGORY, RELEASE_DATE, AVAILABLE, QUANTITY)
VALUES ('Thar', 'Powerful off-road SUV', 'Mahindra', 1400000, 'Cars', '2023-01-05', TRUE, 5);

INSERT INTO PRODUCT (NAME, DESC, BRAND, PRICE, CATEGORY, RELEASE_DATE, AVAILABLE, QUANTITY)
VALUES ('Honda City', 'Comfortable sedan car', 'Honda', 1500000, 'Cars', '2022-11-30', TRUE, 12);
